id: I51524892
legacy_id: 9757a5dccceb4762b888f17b674509e4
ocr_import_info:
  bdrc_scan_id: W2CZ8040
  source: bdrc
  ocr_info:
    timestamp: '2021-09-26T07:01:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:46:37.891529+00:00'
last_modified: 2022-09-02 23:50:07.449892
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ8040
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ8040
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཻ་ཌཱུརྱ་དཀར་པོ།
  author: སྡེ་སྲིད་སངས་རྒྱས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9434696424114941
  ocr_word_median_confidence_index: 0.98
quality: null
bases:
  I1KG12907:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12907
      total_pages: 558
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG12907.txt
    statistics:
      ocr_word_median_confidence_index: 0.98
      ocr_word_mean_confidence_index: 0.9509283304639775
    legacy_id: v002
  I1KG12906:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12906
      total_pages: 490
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12906.txt
    statistics:
      ocr_word_median_confidence_index: 0.98
      ocr_word_mean_confidence_index: 0.934206680654078
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
