id: 9757a5dccceb4762b888f17b674509e4
initial_creation_type: ocr
created_at: 26/09/2021
last_modified_at: 26/11/2021
source_metadata:
  id: bdr:W2CZ8040
  title: བཻ་ཌཱུརྱ་དཀར་པོ།
  volumes:
    4e72d7cb11ed48a1a637393e3ea71a03:
      image_group_id: I1KG12906
      title: ''
      base_file: v001.txt
    38b6dac704274553aa27504ca3452a6e:
      image_group_id: I1KG12907
      title: ''
      base_file: v002.txt
  author: ''
